### ISSUE TITLE
Buttons should not be wrapped in <a> tags

### ISSUE THREAD

**Issue by mandiwise** [redacademy/cdn-adventure-co-winter-2016#1]
This syntax should not be used:

```
<a href="/request">
  <button type="button" class="button">Request To Book</button>
</a>
```

Instead, use something like this:

```
<a href="/request" class="button>Request To Book</a>
```

There are numerous places throughout the site where this needs to be fixed.

**Comment by j-forsythe** [comment]
All <a> tags with button tages have been changed to <a class="button">
