### ISSUE TITLE
Use heading elements in the banners

### ISSUE THREAD

**Issue by mandiwise** [redacademy/cdn-adventure-co-winter-2016#3]
Rather than wrapping your banner text in `<div>` elements, it would make more sense semantically to wrap them in an appropriate level heading tag (e.g. `<h2>`). Also, be careful how you use `<h1>` elements throughout all the pages as these have implications for SEO.

**Comment by camerondfuller** [comment]
Discussed whether or not to make banner text a heading and decided against it. As the styling in the "banner-text" class will override any inherit styling, the choice to change elements is a seemingly arbitrary choice. CF
